INSERT INTO SPITTER  (USERNAME, PASSWORD, FULLNAME) VALUES ('Roma','1','Luch');
INSERT INTO SPITTER (USERNAME, PASSWORD, FULLNAME) VALUES ('Kate','2','Luch');
INSERT INTO SPITTER (USERNAME, PASSWORD, FULLNAME) VALUES ('Yaro','3','Luch');
INSERT INTO SPITTER (USERNAME, PASSWORD, FULLNAME) VALUES ('Alin','4','Luch');
INSERT INTO SPITTER (USERNAME, PASSWORD, FULLNAME) VALUES ('Alex','5','Luch');